workflows:
  ios-workflow:
    name: iOS workflow
    instance_type: mac_mini_m2

    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build iOS IPA
        script: flutter build ipa --release

    artifacts:
      - /Users/builder/clone/build/ios/ipa/*.ipa
      - /Users/builder/clone/build/ios/archive/*.xcarchive