workflows:
  ios-workflow:
    name: iOS workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
